# Generated by Django 4.1.4 on 2023-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newppl", "0003_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=240, verbose_name="Title")),
                ("startdatetime", models.DateTimeField()),
                ("enddatetime", models.DateTimeField()),
                (
                    "timedescription",
                    models.CharField(max_length=240, verbose_name="Time Description"),
                ),
                ("groupsattending", models.IntegerField()),
                ("peopleattending", models.IntegerField()),
                ("slotsopen", models.IntegerField()),
                (
                    "estimateprice",
                    models.CharField(max_length=240, verbose_name="Estimate Price"),
                ),
                ("description", models.TextField()),
                ("minpax", models.IntegerField()),
                ("maxpax", models.IntegerField()),
            ],
        ),
    ]
