# Generated by Django 4.1.4 on 2023-01-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newppl", "0004_events"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
