# Generated by Django 4.1.4 on 2023-01-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newppl", "0006_event_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="groupsattending",
        ),
        migrations.RemoveField(
            model_name="event",
            name="peopleattending",
        ),
        migrations.RemoveField(
            model_name="event",
            name="slotsopen",
        ),
    ]
