# Generated by Django 4.1.4 on 2023-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newppl", "0007_remove_event_groupsattending_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(
                default="default address", max_length=240, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(default="default description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="estimateprice",
            field=models.CharField(
                default="default est price",
                max_length=240,
                verbose_name="Estimate Price",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="maxpax",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="event",
            name="minpax",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="event",
            name="timedescription",
            field=models.CharField(
                default="default time desc",
                max_length=240,
                verbose_name="Time Description",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                default="default title", max_length=240, verbose_name="Title"
            ),
        ),
    ]
