# Generated by Django 4.1.4 on 2023-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newppl", "0008_event_address_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="eventphoto",
            field=models.ImageField(default="blankimage.jpg", upload_to="eventphoto/"),
        ),
    ]
